# Generated by Django 4.0.6 on 2022-07-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='testarea',
            new_name='textarea',
        ),
    ]
