# Generated by Django 4.1 on 2022-08-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogreplay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogReplay',
        ),
    ]
