# Generated by Django 4.1 on 2022-08-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
